{"cells": [{"source": "---  \n# Errors and Exceptions  \nteaching: 30  \nexercises: 0  \nquestions:  \n- \"How does Python report errors?\"  \n- \"How can I handle errors in Python programs?\"  \nobjectives:  \n- \"To be able to read a traceback, and determine where the error took place and what type it is.\"  \n- \"To be able to describe the types of situations in which syntax errors,  \n   indentation errors, name errors, index errors, and missing file errors occur.\"  \nkeypoints:  \n- \"Tracebacks can look intimidating, but they give us a lot of useful information about  \n   what went wrong in our program, including where the error occurred and  \n   what type of error it was.\"  \n- \"An error having to do with the 'grammar' or syntax of the program is called a `SyntaxError`.  \n   If the issue has to do with how the code is indented,  \n   then it will be called an `IndentationError`.\"  \n- \"A `NameError` will occur when trying to use a variable that does not exist. Possible causes are  \n  that a variable definition is missing, a variable reference differs from its definition  \n  in spelling or capitalization, or the code contains a string that is missing quotes around it.\"  \n- \"Containers like lists and strings will generate errors if you try to access items  \n   in them that do not exist. This type of error is called an `IndexError`.\"  \n- \"Trying to read a file that does not exist will give you an `FileNotFoundError`.  \n   Trying to read a file that is open for writing, or writing to a file that is open for reading,  \n   will give you an `IOError`.\"  \n---  \n\nEvery programmer encounters errors,  \nboth those who are just beginning,  \nand those who have been programming for years.  \nEncountering errors and exceptions can be very frustrating at times,  \nand can make coding feel like a hopeless endeavour.  \nHowever,  \nunderstanding what the different types of errors are  \nand when you are likely to encounter them can help a lot.  \nOnce you know *why* you get certain types of errors,  \nthey become much easier to fix.  \n\nErrors in Python have a very specific form,  \ncalled a <span style=\"color:red\" title=\"The sequence of function calls that led to an error.\">traceback</span>  \nLet's examine one:  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"outputs": [], "execution_count": 1, "source": "# This code has an intentional error. You can type it directly or\n# use it for reference to understand the error message below.\ndef favorite_ice_cream():\n    ice_creams = [\n        \"chocolate\",\n        \"vanilla\",\n        \"strawberry\"\n    ]\n    print(ice_creams[3])\n\nfavorite_ice_cream()", "cell_type": "code", "metadata": {"format": "row", "scrolled": false, "collapsed": false}}, {"source": "---  \n```python\n---------------------------------------------------------------------------  \nIndexError                                Traceback (most recent call last)  \n<ipython-input-1-70bd89baa4df> in <module>()  \n      6     print(ice_creams[3])  \n      7  \n----> 8 favorite_ice_cream()  \n\n<ipython-input-1-70bd89baa4df> in favorite_ice_cream()  \n      4         \"vanilla\",                                                                    \"strawberry\"  \n      5     ]  \n----> 6     print(ice_creams[3])  \n      7  \n      8 favorite_ice_cream()  \n\nIndexError: list index out of range  \n```\n---  \n{: .error}  \n\nThis particular traceback has two levels.  \nYou can determine the number of levels by looking for the number of arrows on the left hand side.  \nIn this case:  \n\n1.  The first shows code from the cell above,  \n    with an arrow pointing to Line 8 (which is `favorite_ice_cream()`).  \n\n2.  The second shows some code in the function `favorite_ice_cream`,  \n    with an arrow pointing to Line 6 (which is `print(ice_creams[3])`).  \n\nThe last level is the actual place where the error occurred.  \nThe other level(s) show what function the program executed to get to the next level down.  \nSo, in this case, the program first performed a  \n<span style=\"color:red\" title=\"A use of a function in another piece of software.\">function call</span>  \nInside this function,  \nthe program encountered an error on Line 6, when it tried to run the code `print(ice_creams[3])`.  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"source": "This particular traceback has two levels.  \nYou can determine the number of levels by looking for the number of arrows on the left hand side.  \nIn this case:  \n\n1.  The first shows code from the cell above,  \n    with an arrow pointing to Line 8 (which is `favorite_ice_cream()`).  \n\n2.  The second shows some code in the function `favorite_ice_cream`,  \n    with an arrow pointing to Line 6 (which is `print(ice_creams[3])`).  \n\nThe last level is the actual place where the error occurred.  \nThe other level(s) show what function the program executed to get to the next level down.  \nSo, in this case, the program first performed a  \n<span style=\"color:red\" title=\"A use of a function in another piece of software.\">function call</span>  \nInside this function,  \nthe program encountered an error on Line 6, when it tried to run the code `print(ice_creams[3])`.  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"source": "> ## Long Tracebacks  \n>  \n> Sometimes, you might see a traceback that is very long  \n> -- sometimes they might even be 20 levels deep!  \n> This can make it seem like something horrible happened,  \n> but the length of the error message does not reflect severity, rather,  \n> it indicates that your program called many functions before it encountered the error.  \n> Most of the time, the actual place where the error occurred is at the bottom-most level,  \n> so you can skip down the traceback to the bottom.  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"source": "So what error did the program actually encounter?  \nIn the last line of the traceback,  \nPython helpfully tells us the category or type of error (in this case, it is an `IndexError`)  \nand a more detailed error message (in this case, it says \"list index out of range\").  \n\nIf you encounter an error and don't know what it means,  \nit is still important to read the traceback closely.  \nThat way,  \nif you fix the error,  \nbut encounter a new one,  \nyou can tell that the error changed.  \nAdditionally,  \nsometimes knowing *where* the error occurred is enough to fix it,  \neven if you don't entirely understand the message.  \n\nIf you do encounter an error you don't recognize,  \ntry looking at the  \n[official documentation on errors](http://docs.python.org/3/library/exceptions.html)  \nHowever,  \nnote that you may not always be able to find the error there,  \nas it is possible to create custom errors.  \nIn that case,  \nhopefully the custom error message is informative enough to help you figure out what went wrong.  \n\n## Syntax Errors  \n\nWhen you forget a colon at the end of a line,  \naccidentally add one space too many when indenting under an `if` statement,  \nor forget a parenthesis,  \nyou will encounter a <span style=\"color:red\" title=\"A programming error that occurs when statements are in an order or contain characters  \nnot expected by the programming language.\">syntax error</span>  \nThis means that Python couldn't figure out how to read your program.  \nThis is similar to forgetting punctuation in English:  \nfor example,  \nthis text is difficult to read there is no punctuation there is also no capitalization  \nwhy is this hard because you have to figure out where each sentence ends  \nyou also have to figure out where each sentence begins  \nto some extent it might be ambiguous if there should be a sentence break or not  \n\nPeople can typically figure out what is meant by text with no punctuation,  \nbut people are much smarter than computers.  \nIf Python doesn't know how to read the program,  \nit will give up and inform you with an error.  \nFor example:  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"outputs": [], "execution_count": 1, "source": "def some_function()\n    msg = \"hello, world!\"\n    print(msg)\n     return msg", "cell_type": "code", "metadata": {"format": "row", "scrolled": false, "collapsed": false}}, {"source": "---  \n```python\n  File \"<ipython-input-3-6bb841ea1423>\", line 1  \n    def some_function()  \n                       ^  \nSyntaxError: invalid syntax  \n```\n---  \n{: .error}  \n\nHere, Python tells us that there is a `SyntaxError` on line 1,  \nand even puts a little arrow in the place where there is an issue.  \nIn this case the problem is that the function definition is missing a colon at the end.  \n\nActually, the function above has *two* issues with syntax.  \nIf we fix the problem with the colon,  \nwe see that there is *also* an `IndentationError`,  \nwhich means that the lines in the function definition do not all have the same indentation:  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"source": "Here, Python tells us that there is a `SyntaxError` on line 1,  \nand even puts a little arrow in the place where there is an issue.  \nIn this case the problem is that the function definition is missing a colon at the end.  \n\nActually, the function above has *two* issues with syntax.  \nIf we fix the problem with the colon,  \nwe see that there is *also* an `IndentationError`,  \nwhich means that the lines in the function definition do not all have the same indentation:  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"outputs": [], "execution_count": 1, "source": "def some_function():\n    msg = \"hello, world!\"\n    print(msg)\n     return msg", "cell_type": "code", "metadata": {"format": "row", "scrolled": false, "collapsed": false}}, {"source": "---  \n```python\n  File \"<ipython-input-4-ae290e7659cb>\", line 4  \n    return msg  \n    ^  \nIndentationError: unexpected indent  \n```\n---  \n{: .error}  \n\nBoth `SyntaxError` and `IndentationError` indicate a problem with the syntax of your program,  \nbut an `IndentationError` is more specific:  \nit *always* means that there is a problem with how your code is indented.  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"source": "Both `SyntaxError` and `IndentationError` indicate a problem with the syntax of your program,  \nbut an `IndentationError` is more specific:  \nit *always* means that there is a problem with how your code is indented.  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"source": "> ## Tabs and Spaces  \n>  \n> Some indentation errors are harder to spot than others.  \n> In particular, mixing spaces and tabs can be difficult to spot  \n> because they are both <span style=\"color:red\" title=\"\">whitespace</span>  \n> In the example below, the first two lines in the body of the function  \n> `some_function` are indented with tabs, while the third line &mdash; with spaces.  \n> If you're working in a Jupyter notebook, be sure to copy and paste this example  \n> rather than trying to type it in manually because Jupyter automatically replaces  \n> tabs with spaces.  \n>  \n> ---  \n```python\n> def some_function():  \n> \tmsg = \"hello, world!\"  \n> \tprint(msg)  \n>         return msg  \n```\n> ---  \n> \n>  \n> Visually it is impossible to spot the error.  \n> Fortunately, Python does not allow you to mix tabs and spaces.  \n>  \n> ---  \n```python\n>   File \"<ipython-input-5-653b36fbcd41>\", line 4  \n>     return msg  \n>               ^  \n> TabError: inconsistent use of tabs and spaces in indentation  \n```\n> ---  \n> {: .error}  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"source": "## Variable Name Errors  \n\nAnother very common type of error is called a `NameError`,  \nand occurs when you try to use a variable that does not exist.  \nFor example:  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"outputs": [], "execution_count": 1, "source": "print(a)", "cell_type": "code", "metadata": {"format": "row", "scrolled": false, "collapsed": false}}, {"source": "---  \n```python\n---------------------------------------------------------------------------  \nNameError                                 Traceback (most recent call last)  \n<ipython-input-7-9d7b17ad5387> in <module>()  \n----> 1 print(a)  \n\nNameError: name 'a' is not defined  \n```\n---  \n{: .error}  \n\nVariable name errors come with some of the most informative error messages,  \nwhich are usually of the form \"name 'the_variable_name' is not defined\".  \n\nWhy does this error message occur?  \nThat's a harder question to answer,  \nbecause it depends on what your code is supposed to do.  \nHowever,  \nthere are a few very common reasons why you might have an undefined variable.  \nThe first is that you meant to use a  \n<span style=\"color:red\" title=\"Short for \"character string\",  \na sequence of zero or more characters.\">string</span>  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"source": "Variable name errors come with some of the most informative error messages,  \nwhich are usually of the form \"name 'the_variable_name' is not defined\".  \n\nWhy does this error message occur?  \nThat's a harder question to answer,  \nbecause it depends on what your code is supposed to do.  \nHowever,  \nthere are a few very common reasons why you might have an undefined variable.  \nThe first is that you meant to use a  \n<span style=\"color:red\" title=\"Short for \"character string\",  \na sequence of zero or more characters.\">string</span>  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"outputs": [], "execution_count": 1, "source": "print(hello)", "cell_type": "code", "metadata": {"format": "row", "scrolled": false, "collapsed": false}}, {"source": "---  \n```python\n---------------------------------------------------------------------------  \nNameError                                 Traceback (most recent call last)  \n<ipython-input-8-9553ee03b645> in <module>()  \n----> 1 print(hello)  \n\nNameError: name 'hello' is not defined  \n```\n---  \n{: .error}  \n\nThe second reason is that you might be trying to use a variable that does not yet exist.  \nIn the following example,  \n`count` should have been defined (e.g., with `count = 0`) before the for loop:  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"source": "The second reason is that you might be trying to use a variable that does not yet exist.  \nIn the following example,  \n`count` should have been defined (e.g., with `count = 0`) before the for loop:  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"outputs": [], "execution_count": 1, "source": "for number in range(10):\n    count = count + number\nprint(\"The count is:\", count)", "cell_type": "code", "metadata": {"format": "row", "scrolled": false, "collapsed": false}}, {"source": "---  \n```python\n---------------------------------------------------------------------------  \nNameError                                 Traceback (most recent call last)  \n<ipython-input-9-dd6a12d7ca5c> in <module>()  \n      1 for number in range(10):  \n----> 2     count = count + number  \n      3 print(\"The count is:\", count)  \n\nNameError: name 'count' is not defined  \n```\n---  \n{: .error}  \n\nFinally, the third possibility is that you made a typo when you were writing your code.  \nLet's say we fixed the error above by adding the line `Count = 0` before the for loop.  \nFrustratingly, this actually does not fix the error.  \nRemember that variables are <span style=\"color:red\" title=\"Treating text as if upper and lower case characters of the same letter are different.  \nSee also: case-insensitive.\">case-sensitive</span>  \nso the variable `count` is different from `Count`. We still get the same error,  \nbecause we still have not defined `count`:  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"source": "Finally, the third possibility is that you made a typo when you were writing your code.  \nLet's say we fixed the error above by adding the line `Count = 0` before the for loop.  \nFrustratingly, this actually does not fix the error.  \nRemember that variables are <span style=\"color:red\" title=\"Treating text as if upper and lower case characters of the same letter are different.  \nSee also: case-insensitive.\">case-sensitive</span>  \nso the variable `count` is different from `Count`. We still get the same error,  \nbecause we still have not defined `count`:  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"outputs": [], "execution_count": 1, "source": "Count = 0\nfor number in range(10):\n    count = count + number\nprint(\"The count is:\", count)", "cell_type": "code", "metadata": {"format": "row", "scrolled": false, "collapsed": false}}, {"source": "---  \n```python\n---------------------------------------------------------------------------  \nNameError                                 Traceback (most recent call last)  \n<ipython-input-10-d77d40059aea> in <module>()  \n      1 Count = 0  \n      2 for number in range(10):  \n----> 3     count = count + number  \n      4 print(\"The count is:\", count)  \n\nNameError: name 'count' is not defined  \n```\n---  \n{: .error}  \n\n## Index Errors  \n\nNext up are errors having to do with containers (like lists and strings) and the items within them.  \nIf you try to access an item in a list or a string that does not exist,  \nthen you will get an error.  \nThis makes sense:  \nif you asked someone what day they would like to get coffee,  \nand they answered \"caturday\",  \nyou might be a bit annoyed.  \nPython gets similarly annoyed if you try to ask it for an item that doesn't exist:  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"source": "## Index Errors  \n\nNext up are errors having to do with containers (like lists and strings) and the items within them.  \nIf you try to access an item in a list or a string that does not exist,  \nthen you will get an error.  \nThis makes sense:  \nif you asked someone what day they would like to get coffee,  \nand they answered \"caturday\",  \nyou might be a bit annoyed.  \nPython gets similarly annoyed if you try to ask it for an item that doesn't exist:  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"outputs": [{"execution_count": 1, "data": {"text/plain": ["Letter #1 is a", "Letter #2 is b", "Letter #3 is c"]}, "output_type": "execute_result", "metadata": {}}], "execution_count": 1, "source": "letters = ['a', 'b', 'c']\nprint(\"Letter #1 is\", letters[0])\nprint(\"Letter #2 is\", letters[1])\nprint(\"Letter #3 is\", letters[2])\nprint(\"Letter #4 is\", letters[3])", "cell_type": "code", "metadata": {"format": "row", "scrolled": false, "collapsed": false}}, {"source": "---  \n```python\n---------------------------------------------------------------------------  \nIndexError                                Traceback (most recent call last)  \n<ipython-input-11-d817f55b7d6c> in <module>()  \n      3 print(\"Letter #2 is\", letters[1])  \n      4 print(\"Letter #3 is\", letters[2])  \n----> 5 print(\"Letter #4 is\", letters[3])  \n\nIndexError: list index out of range  \n```\n---  \n{: .error}  \n\nHere,  \nPython is telling us that there is an `IndexError` in our code,  \nmeaning we tried to access a list index that did not exist.  \n\n## File Errors  \n\nThe last type of error we'll cover today  \nare those associated with reading and writing files: `FileNotFoundError`.  \nIf you try to read a file that does not exist,  \nyou will receive a `FileNotFoundError` telling you so.  \nIf you attempt to write to a file that was opened read-only, Python 3  \nreturns an `UnsupportedOperationError`.  \nMore generally, problems with input and output manifest as  \n`IOError`s or `OSError`s, depending on the version of Python you use.  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"source": "Here,  \nPython is telling us that there is an `IndexError` in our code,  \nmeaning we tried to access a list index that did not exist.  \n\n## File Errors  \n\nThe last type of error we'll cover today  \nare those associated with reading and writing files: `FileNotFoundError`.  \nIf you try to read a file that does not exist,  \nyou will receive a `FileNotFoundError` telling you so.  \nIf you attempt to write to a file that was opened read-only, Python 3  \nreturns an `UnsupportedOperationError`.  \nMore generally, problems with input and output manifest as  \n`IOError`s or `OSError`s, depending on the version of Python you use.  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"outputs": [], "execution_count": 1, "source": "file_handle = open('myfile.txt', 'r')", "cell_type": "code", "metadata": {"format": "row", "scrolled": false, "collapsed": false}}, {"source": "---  \n```python\n---------------------------------------------------------------------------  \nFileNotFoundError                         Traceback (most recent call last)  \n<ipython-input-14-f6e1ac4aee96> in <module>()  \n----> 1 file_handle = open('myfile.txt', 'r')  \n\nFileNotFoundError: [Errno 2] No such file or directory: 'myfile.txt'  \n```\n---  \n{: .error}  \n\nOne reason for receiving this error is that you specified an incorrect path to the file.  \nFor example,  \nif I am currently in a folder called `myproject`,  \nand I have a file in `myproject/writing/myfile.txt`,  \nbut I try to open `myfile.txt`,  \nthis will fail.  \nThe correct path would be `writing/myfile.txt`.  \nIt is also possible that the file name or its path contains a typo.  \n\nA related issue can occur if you use the \"read\" flag instead of the \"write\" flag.  \nPython will not give you an error if you try to open a file for writing  \nwhen the file does not exist.  \nHowever,  \nif you meant to open a file for reading,  \nbut accidentally opened it for writing,  \nand then try to read from it,  \nyou will get an `UnsupportedOperation` error  \ntelling you that the file was not opened for reading:  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"source": "One reason for receiving this error is that you specified an incorrect path to the file.  \nFor example,  \nif I am currently in a folder called `myproject`,  \nand I have a file in `myproject/writing/myfile.txt`,  \nbut I try to open `myfile.txt`,  \nthis will fail.  \nThe correct path would be `writing/myfile.txt`.  \nIt is also possible that the file name or its path contains a typo.  \n\nA related issue can occur if you use the \"read\" flag instead of the \"write\" flag.  \nPython will not give you an error if you try to open a file for writing  \nwhen the file does not exist.  \nHowever,  \nif you meant to open a file for reading,  \nbut accidentally opened it for writing,  \nand then try to read from it,  \nyou will get an `UnsupportedOperation` error  \ntelling you that the file was not opened for reading:  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"outputs": [], "execution_count": 1, "source": "file_handle = open('myfile.txt', 'w')\nfile_handle.read()", "cell_type": "code", "metadata": {"format": "row", "scrolled": false, "collapsed": false}}, {"source": "---  \n```python\n---------------------------------------------------------------------------  \nUnsupportedOperation                      Traceback (most recent call last)  \n<ipython-input-15-b846479bc61f> in <module>()  \n      1 file_handle = open('myfile.txt', 'w')  \n----> 2 file_handle.read()  \n\nUnsupportedOperation: not readable  \n```\n---  \n{: .error}  \n\nThese are the most common errors with files,  \nthough many others exist.  \nIf you get an error that you've never seen before,  \nsearching the Internet for that error type  \noften reveals common reasons why you might get that error.  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"source": "These are the most common errors with files,  \nthough many others exist.  \nIf you get an error that you've never seen before,  \nsearching the Internet for that error type  \noften reveals common reasons why you might get that error.  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"source": "## Reading Error Messages  \n\nRead the Python code and the resulting traceback below, and answer the following questions:  \n\n1.  How many levels does the traceback have?  \n2.  What is the function name where the error occurred?  \n3.  On which line number in this function did the error occur?  \n4.  What is the type of error?  \n5.  What is the error message?  \n\n---  \n```python\n# This code has an intentional error. Do not type it directly;  \n# use it for reference to understand the error message below.  \ndef print_message(day):  \nmessages = {  \n\"monday\": \"Hello, world!\",  \n\"tuesday\": \"Today is Tuesday!\",  \n\"wednesday\": \"It is the middle of the week.\",  \n\"thursday\": \"Today is Donnerstag in German!\",  \n\"friday\": \"Last day of the week!\",  \n\"saturday\": \"Hooray for the weekend!\",  \n\"sunday\": \"Aw, the weekend is almost over.\"  \n}  \nprint(messages[day])  \n\ndef print_friday_message():  \nprint_message(\"Friday\")  \n\nprint_friday_message()  \n```\n---  \n\n\n---  \n```python\n---------------------------------------------------------------------------  \nKeyError                                  Traceback (most recent call last)  \n<ipython-input-1-4be1945adbe2> in <module>()  \n14     print_message(\"Friday\")  \n15  \n---> 16 print_friday_message()  \n\n<ipython-input-1-4be1945adbe2> in print_friday_message()  \n12  \n13 def print_friday_message():  \n---> 14     print_message(\"Friday\")  \n15  \n16 print_friday_message()  \n\n<ipython-input-1-4be1945adbe2> in print_message(day)  \n9         \"sunday\": \"Aw, the weekend is almost over.\"  \n10     }  \n---> 11     print(messages[day])  \n12  \n13 def print_friday_message():  \n\nKeyError: 'Friday'  \n```\n---  \n{: .error}  \n\n<details>  \n<summary><b> Solution</b></summary>  \n\n1. 3 levels  \n2. `print_message`  \n3. 11  \n4. `KeyError`  \n5. There isn't really a message; you're supposed to infer that `Friday` is not a key in `messages`.  \n</details>  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"source": "## Identifying Syntax Errors  \n\n1. Read the code below, and (without running it) try to identify what the errors are.  \n2. Run the code, and read the error message. Is it a `SyntaxError` or an `IndentationError`?  \n3. Fix the error.  \n4. Repeat steps 2 and 3, until you have fixed all the errors.  \n\n---  \n```python\ndef another_function  \nprint(\"Syntax errors are annoying.\")  \nprint(\"But at least Python tells us about them!\")  \nprint(\"So they are usually not too hard to fix.\")  \n```\n---  \n\n\n## Solution  \n`SyntaxError` for missing `():` at end of first line,  \n`IndentationError` for mismatch between second and third lines.  \n<details>  \n<summary><b>A fixed version is:</b></summary>  \n\n\n---  \n```python\ndef another_function():  \nprint(\"Syntax errors are annoying.\")  \nprint(\"But at least Python tells us about them!\")  \nprint(\"So they are usually not too hard to fix.\")  \n```\n---  \n\n</details>  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"source": "## Identifying Variable Name Errors  \n\n1. Read the code below, and (without running it) try to identify what the errors are.  \n2. Run the code, and read the error message.  \nWhat type of `NameError` do you think this is?  \nIn other words, is it a string with no quotes,  \na misspelled variable,  \nor a variable that should have been defined but was not?  \n3. Fix the error.  \n4. Repeat steps 2 and 3, until you have fixed all the errors.  \n\n---  \n```python\nfor number in range(10):  \n# use a if the number is a multiple of 3, otherwise use b  \nif (Number % 3) == 0:  \nmessage = message + a  \nelse:  \nmessage = message + \"b\"  \nprint(message)  \n```\n---  \n\n\n<details>  \n<summary><b> Solution</b></summary>  \n\n3 `NameError`s for `number` being misspelled, for `message` not defined,  \nand for `a` not being in quotes.  \n\nFixed version:  \n\n---  \n```python\nmessage = \"\"  \nfor number in range(10):  \n# use a if the number is a multiple of 3, otherwise use b  \nif (number % 3) == 0:  \nmessage = message + \"a\"  \nelse:  \nmessage = message + \"b\"  \nprint(message)  \n```\n---  \n\n</details>  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}, {"source": "## Identifying Index Errors  \n\n1. Read the code below, and (without running it) try to identify what the errors are.  \n2. Run the code, and read the error message. What type of error is it?  \n3. Fix the error.  \n\n---  \n```python\nseasons = ['Spring', 'Summer', 'Fall', 'Winter']  \nprint('My favorite season is ', seasons[4])  \n```\n---  \n\n\n<details>  \n<summary><b> Solution</b></summary>  \n\n`IndexError`; the last entry is `seasons[3]`, so `seasons[4]` doesn't make sense.  \nA fixed version is:  \n\n---  \n```python\nseasons = ['Spring', 'Summer', 'Fall', 'Winter']  \nprint('My favorite season is ', seasons[-1])  \n```\n---  \n\n</details>  \n", "cell_type": "markdown", "metadata": {}, "attachments": {}}], "nbformat_minor": 0, "nbformat": 4, "metadata": {}}